$('.logo-carousel').owlCarousel({
    loop:true,
    autoplay:true,
    responsive:{
        0:{
            items:3
        },
        200:{
            items:3
        },
        400:{
            items:3
        },
        700:{
            items:4
        },
        900:{
            items:6
        }
    }
})